export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const HEXAGRAM_GENERATE_KUA = 'HEXAGRAM_GENERATE_KUA';
export const HEXAGRAM_GENERATED = 'HEXAGRAM_GENERATED';
export const HEXAGRAM_RESET = 'HEXAGRAM_RESET';
