/** Play page */
export const PLAY_SET_HEXAGRAM = 'PLAY_SET_HEXAGRAM';
export const PLAY_CLEAR_HEXAGRAM = 'PLAY_CLEAR_HEXAGRAM';

/** Details page */
export const DETAILS_SET_HEXAGRAM = 'DETAILS_SET_HEXAGRAM';

export const ICHING_BOOK_LOAD = 'ICHING_BOOK_LOAD_JSON';
export const ICHING_BOOK_LOADED = 'ICHING_BOOK_LOADED';

export const I18N_SET_LANGUAGE = 'I18N_SET_LANGUAGE';